import Header from "@/components/_dashboard/dashboard-header";
import { Sidebar } from "@/components/_dashboard/SideBar";
import { AdminDashboardTabsList } from "@/data/data";
import type { Metadata } from "next";
import "../globals.css";

import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import ProtectedRoute from "@/components/common/ProtectedRoute";

// import ProtectedRoute from "@/components/auth/ProtectedRoute";

export const metadata: Metadata = {
  title: "Psykick Club",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ProtectedRoute>
      <div className="flex h-screen overflow-hidden">
        {/* Sidebar fixed on the left */}
        <div className="fixed inset-y-0 left-0 w-[272px]  z-50">
          <Sidebar lists={AdminDashboardTabsList} />
        </div>

        {/* Main content area */}
        <div className="flex-1 ml-[272px] flex flex-col backdrop-blur-sm bg-[#371B77]/40 dashboard-shadow overflow-y-auto">
          <Header />
          <main className="flex-1 p-4">{children}</main>
          <ToastContainer position="top-right" autoClose={3000} />
        </div>
      </div>
    </ProtectedRoute>
  );
}
